services:
  postgres:
    container_name: postgress-book
    image: postgres
    environment:
      POSTGRES_USER: ameda
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: books
    volumes:
      - postgres:/data/postgres
    ports:
      - "5480:5432"
    networks:
      - books-network
    restart: unless-stopped

  pgadmin:
    container_name: postgres-GUI
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - books-network
    restart: unless-stopped


  mail-dev:
    container_name: mail-dev-books
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  books-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
    driver: local
