services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: ameda
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/datadocker
      POSTGRES_DB: books
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - books-project
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  books-project:
    driver: bridge

volumes:
  postgres:
    driver: local
